language: python
python:
  - "2.7"
install: pip install -r requirements.txt -r test-requirements.txt
services: postgresql
before_script:
    - psql -U postgres -c "create user asterisk with password 'asterisk';"
    - psql -U postgres -c "create database asterisktest owner asterisk;"
script: nosetests xivo_dao
notifications:
  email:
    recipients:
      - dev+tests-reports@proformatique.com
    on_success: change
    on_failure: change
branches:
  only:
    - master
sudo: false
