db:
  image: postgres
  ports:
   - "5432"
  environment:
   - POSTGRES_USER=asterisk
   - POSTGRES_PASSWORD=proformatique
   - POSTGRES_DB=asterisk
  volumes:
    - "./contribs/docker/db/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql"
