db:
  image: postgres
  expose:
   - "5432"
  environment:
   - POSTGRES_USER=asterisk
   - POSTGRES_PASSWORD=proformatique
   - POSTGRES_DB=asterisk
  volumes:
    - "./contribs/docker/db/uuid.sql:/docker-entrypoint-initdb.d/uuid.sql"
dao:
  build: .
  links:
    - db
  environment:
    - XIVO_TEST_DB_URL=postgresql://asterisk:proformatique@db/asterisk
  volumes:
    - "./xivo_dao:/usr/src/dao/xivo_dao"
