---
- name: Start DB container
  command: docker-compose up -d
  args:
    chdir: "{{ zuul.project.src_dir }}"
- name: Get DB container port
  command: docker-compose port db 5432
  register: container_port
  args:
    chdir: "{{ zuul.project.src_dir }}"
- name: Export DB container port
  set_fact:
    tox_environment:
      XIVO_TEST_DB_URL: "postgresql://asterisk:proformatique@{{ container_port.stdout }}/asterisk"
- name: Show DB container URL
  debug:
    var: tox_environment
