---
# This file was copied from wazo-production-sf-jobs/playbooks/wazo-tox/run.yaml
# Modification: add role xivo-dao-db to start the DB container

- hosts: all
  roles:
      - revoke-sudo
      - xivo-dao-db
      - wazo-tox
